### ISSUE TITLE
unbound column

### ISSUE THREAD

**Issue by saad657** [DevExpress-Examples/how-to-create-and-populate-an-unbound-column-e3354#1]
hi i have followed this tutorial
in my scene i am giving gridcontrol datasource at runtime and created an unbound column but i am not getting how to cache unbound column like you are using in this project...?

**Comment by AlexGreenZ** [comment]
Hello,

As for technical issues, it is better to contact us via the [Support Center](www.devexpress.com/support/center). Feel free to describe your scenario in greater detail so that we can provide you with a suitable solution. If you also attach a small sample demonstrating your project's current state, we will find a suitable solution faster.
